"""Build the dashboard (``dashboard.md`` + ``dashboard.html``) from the registry.

For each instance, the board shows the figure count, the stack the figures were
rendered with, the manifest's generated date, freshness against the library's
latest release, and a thumbnail grid. Every thumbnail links to the raw PNG in
the project repo. Each figure also carries a copyable ``/eyes review <instance>
<figure>`` line. The board embeds no image bytes and copies no files.

The output is deterministic: it has no wall-clock stamp, so a re-render on
unchanged inputs changes nothing and the daily refresh commits nothing. Each
instance section carries an ``eyes:instance`` marker with the manifest digest,
and ``check`` uses that marker to tell whether the committed dashboard is
current.
"""

from __future__ import annotations

import html
import json
import re
import urllib.error
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from eyes import ORGAN_ROOT
from eyes import manifest as manifest_mod
from eyes.registry import Instance

PAGES_URL = "https://pyautolabs.github.io/PyAutoEyes/"
PYPI_JSON = "https://pypi.org/pypi/{name}/json"
MARKER = re.compile(r"<!-- eyes:instance name=(\S+) manifest=(\S+) -->")


@dataclass
class InstanceView:
    instance: Instance
    manifest: manifest_mod.Manifest | None
    error: str | None
    latest: str | None  # latest released library version, None if unknown

    @property
    def digest(self) -> str:
        return self.manifest.digest if self.manifest else "unavailable"

    @property
    def rendered(self) -> str | None:
        if not self.manifest:
            return None
        return self.manifest.rendered_with.get(self.instance.import_name)

    @property
    def freshness(self) -> str:
        if not self.manifest:
            return "unknown (no manifest)"
        if self.latest is None:
            return "unknown (release lookup offline)"
        if self.rendered is None:
            return f"unknown (manifest has no {self.instance.import_name} version)"
        if self.rendered == self.latest:
            return f"current ({self.latest})"
        if _version_key(self.rendered) > _version_key(self.latest):
            return f"ahead of release (rendered {self.rendered}, released {self.latest})"
        return f"behind (rendered {self.rendered}, released {self.latest})"


def _version_key(version: str):
    return tuple(int(p) if p.isdigit() else -1 for p in re.split(r"[.+-]", version))


def latest_release(import_name: str) -> str | None:
    """The library's latest version on PyPI, or None when the lookup fails."""
    try:
        data = json.loads(manifest_mod._http_get(PYPI_JSON.format(name=import_name)))
        return str(data["info"]["version"])
    except (urllib.error.URLError, OSError, ValueError, KeyError, TypeError):
        return None


def collect(instances, sources=None, offline=False, release_lookup=latest_release):
    """Read every instance's manifest (and its latest release, when online)."""
    sources = sources or {}
    views = []
    for inst in instances:
        try:
            man = manifest_mod.load(inst, sources.get(inst.name), offline=offline)
            error = None
        except manifest_mod.ManifestError as exc:
            man, error = None, str(exc)
        latest = None if offline else release_lookup(inst.import_name)
        views.append(InstanceView(inst, man, error, latest))
    return views


def review_line(inst: Instance, fig) -> str:
    return f"/eyes review {inst.name} {fig.file}"


def _grouped(man):
    groups = defaultdict(list)
    for fig in man.figures:
        groups[fig.domain].append(fig)
    return groups


def _figure_label(fig) -> str:
    name = Path(fig.file).name
    return f"{fig.source}/{name}" if fig.source else name


# ------------------------------------------------------------------ markdown ---


def render_markdown(views) -> str:
    out = [
        "# PyAutoEyes — visualization dashboard",
        "",
        "<!-- Generated by `bin/pyauto-eyes board` from registry.yaml and each instance's "
        "tracked manifest. Do not edit by hand. -->",
        "",
        "The cross-project view of the organism's figures. Each `<lib>_visualization` "
        "project repo makes, stores and tracks its figures. This page reads each repo's "
        "tracked manifest and links to the PNGs where they live: it copies nothing, "
        "renders nothing and judges nothing.",
        f"Thumbnails and one-tap copy: [{PAGES_URL}]({PAGES_URL}).",
        "",
        "| Instance | Library | Figures | Rendered with | Generated | Freshness | Gallery |",
        "|----------|---------|--------:|---------------|-----------|-----------|---------|",
    ]
    for v in views:
        inst = v.instance
        if v.manifest:
            count = str(len(v.manifest.figures))
            rendered = f"`{inst.import_name} {v.rendered}`" if v.rendered else "—"
            generated = v.manifest.generated
        else:
            count, rendered, generated = "—", "—", "—"
        out.append(
            f"| [{inst.name}](#{inst.name}) | {inst.library} | {count} | {rendered} | "
            f"{generated} | {v.freshness} | [{inst.gallery}]({inst.gallery_url}) |"
        )
    for v in views:
        inst = v.instance
        out += [
            "",
            f"## {inst.name}",
            "",
            f"<!-- eyes:instance name={inst.name} manifest={v.digest} -->",
            f"{inst.library} figures from [{inst.github}]({inst.github_url}) "
            f"(manifest `{inst.manifest}`; re-rendered on `{inst.dispatch_event}`).",
            "",
        ]
        if not v.manifest:
            out.append(f"**Manifest unavailable:** {v.error}")
            continue
        stack = ", ".join(f"{k} {val}" for k, val in v.manifest.rendered_with.items())
        out += [f"Rendered with {stack}; generated {v.manifest.generated}.", ""]
        for domain, figs in _grouped(v.manifest).items():
            out += [
                f"### {inst.name} / {domain}",
                "",
                "| Figure | Review |",
                "|--------|--------|",
            ]
            for fig in figs:
                out.append(
                    f"| [{_figure_label(fig)}]({inst.image_url(fig.file)}) "
                    f"| `{review_line(inst, fig)}` |"
                )
            out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# ---------------------------------------------------------------------- html ---

CSS = """
:root{--bg:#ffffff;--fg:#1f2328;--muted:#59636e;--card:#f6f8fa;--line:#d1d9e0;
--accent:#b4530a;--hero1:#3a1d05;--hero2:#0b0703;--glow:#ff9d3c;--ok:#1a7f37;--warn:#9a6700}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--bg:#0d1117;--fg:#e6edf3;
--muted:#9198a1;--card:#151b23;--line:#3d444d;--accent:#ffa657;--ok:#3fb950;--warn:#d29922}}
:root[data-theme="dark"]{--bg:#0d1117;--fg:#e6edf3;--muted:#9198a1;--card:#151b23;
--line:#3d444d;--accent:#ffa657;--ok:#3fb950;--warn:#d29922}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);
font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif}
main{max-width:1200px;margin:0 auto;padding:0 16px 48px}
.hero{background:radial-gradient(circle at 30% 20%,var(--hero1),var(--hero2));color:#fff;
padding:28px 16px 22px;text-align:center}
.hero h1{margin:0;font-size:28px;letter-spacing:.5px}.hero h1 span{color:var(--glow)}
.hero p{margin:6px 0 0;color:#d8c9bb;font-size:13px;letter-spacing:2px;text-transform:uppercase}
h2,h3{color:var(--accent)}h2{border-bottom:1px solid var(--line);padding-bottom:4px;margin-top:32px}
a{color:var(--accent)}
.lede{color:var(--muted)}
.tablewrap{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:14px}
th,td{border-bottom:1px solid var(--line);padding:6px 8px;text-align:left;vertical-align:top}
.ok{color:var(--ok)}.warn{color:var(--warn)}.muted{color:var(--muted)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px}
.fig{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:8px;
display:flex;flex-direction:column;gap:6px;min-width:0}
.fig img{width:100%;height:140px;object-fit:contain;background:#fff;border-radius:4px}
.fig .name{font-size:13px;word-break:break-all}
.fig button{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;text-align:left;
background:var(--bg);color:var(--fg);border:1px solid var(--line);border-radius:6px;
padding:4px 6px;cursor:pointer;word-break:break-all}
.fig button.copied{border-color:var(--ok)}
code{color:var(--accent)}
"""

JS = """
document.querySelectorAll('button[data-copy]').forEach(function(b){
  b.addEventListener('click',function(){
    var t=b.getAttribute('data-copy');
    var done=function(){b.classList.add('copied');setTimeout(function(){b.classList.remove('copied')},1200)};
    if(navigator.clipboard){navigator.clipboard.writeText(t).then(done,function(){})}
  });
});
"""


def _e(value) -> str:
    return html.escape(str(value), quote=True)


def _freshness_class(text: str) -> str:
    if text.startswith("current"):
        return "ok"
    if text.startswith("behind"):
        return "warn"
    return "muted"


def render_html(views) -> str:
    rows = []
    for v in views:
        inst = v.instance
        count = str(len(v.manifest.figures)) if v.manifest else "—"
        rendered = f"{inst.import_name} {v.rendered}" if v.rendered else "—"
        generated = v.manifest.generated if v.manifest else "—"
        rows.append(
            f"<tr><td><a href='#{_e(inst.name)}'>{_e(inst.name)}</a></td><td>{_e(inst.library)}</td>"
            f"<td>{count}</td><td><code>{_e(rendered)}</code></td><td>{_e(generated)}</td>"
            f"<td class='{_freshness_class(v.freshness)}'>{_e(v.freshness)}</td>"
            f"<td><a href='{_e(inst.gallery_url)}'>{_e(inst.gallery)}</a></td></tr>"
        )
    sections = []
    for v in views:
        inst = v.instance
        head = (
            f"<h2 id='{_e(inst.name)}'>{_e(inst.name)} · {_e(inst.library)}</h2>"
            f"<p class='lede'>Figures from <a href='{_e(inst.github_url)}'>{_e(inst.github)}</a>, "
            f"manifest <code>{_e(inst.manifest)}</code>, re-rendered on "
            f"<code>{_e(inst.dispatch_event)}</code>.</p>"
        )
        if not v.manifest:
            sections.append(head + f"<p class='warn'>Manifest unavailable: {_e(v.error)}</p>")
            continue
        stack = ", ".join(f"{k} {val}" for k, val in v.manifest.rendered_with.items())
        body = [
            head,
            f"<p class='muted'>Rendered with {_e(stack)}; generated {_e(v.manifest.generated)}.</p>",
        ]
        for domain, figs in _grouped(v.manifest).items():
            cards = []
            for fig in figs:
                url = inst.image_url(fig.file)
                line = review_line(inst, fig)
                cards.append(
                    "<div class='fig'>"
                    f"<a href='{_e(url)}' target='_blank' rel='noopener'>"
                    f"<img loading='lazy' src='{_e(url)}' alt='{_e(fig.file)}'></a>"
                    f"<span class='name'>{_e(_figure_label(fig))}</span>"
                    f"<button type='button' data-copy='{_e(line)}' title='Copy for Claude'>{_e(line)}</button>"
                    "</div>"
                )
            body.append(f"<h3>{_e(domain)}</h3><div class='grid'>{''.join(cards)}</div>")
        sections.append("".join(body))
    return (
        "<!doctype html>\n<html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>PyAutoEyes dashboard</title>"
        "<!-- Generated by `bin/pyauto-eyes board`. Do not edit by hand. -->"
        f"<style>{CSS}</style></head><body>"
        "<header class='hero'><h1>PyAuto<span>Eyes</span></h1><p>See. Compare. Improve.</p></header>"
        "<main><p class='lede'>The cross-project view of the organism's figures. Each "
        "<code>&lt;lib&gt;_visualization</code> project repo makes, stores and tracks its figures. "
        "This page links to them where they live. Tap a thumbnail for the full-size PNG, "
        "or tap its line to copy a review request for Claude.</p>"
        "<div class='tablewrap'><table><thead><tr><th>Instance</th><th>Library</th><th>Figures</th>"
        "<th>Rendered with</th><th>Generated</th><th>Freshness</th><th>Gallery</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div>"
        f"{''.join(sections)}</main><script>{JS}</script></body></html>\n"
    )


# -------------------------------------------------------------------- output ---


def write(views, out_dir: Path = ORGAN_ROOT) -> list[Path]:
    out_dir = Path(out_dir)
    md, page = out_dir / "dashboard.md", out_dir / "dashboard.html"
    md.write_text(render_markdown(views))
    page.write_text(render_html(views))
    return [md, page]


def markers(text: str) -> dict[str, str]:
    """``{instance name: manifest digest}`` as recorded in a rendered dashboard.md."""
    return dict(MARKER.findall(text))
